name: Windows Build

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-2019
    env:
      vcpkg_ref: cd5e746ec203c8c3c61647e0886a8df8c1e78e41
      BOOST_ROOT: ${{github.workspace}}/3rdparty/boost
      BOOST_URL: https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.bz2/download
      QT_ROOT: ${{github.workspace}}/3rdparty/qt
      QT_URL: https://github.com/shun-iwasawa/qt5/releases/download/v5.15.2_wintab/Qt5.15.2_wintab.zip
      LTIFF: ${{github.workspace}}/thirdparty/tiff-4.0.3/lib/LibTIFF-4.0.3_2015_64.lib
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd C:/vcpkg/installed/x64-windows/bin
        ls
        cd toonz
        mkdir build | Out-Null
        cd build
        $env:BOOST_ROOT = '${{ env.BOOST_ROOT }}'
        $env:QT_PATH = '${{ env.QT_ROOT }}/Qt5.15.2_wintab/5.15.2_wintab/msvc2019_64'
        cmake ../sources -G 'Visual Studio 16 2019' -Ax64 -DCMAKE_TOOLCHAIN_FILE='C:/vcpkg/scripts/buildsystems/vcpkg.cmake' -Dquirc_DIR='C:/vcpkg/installed/x64-windows/share/quirc/' -DTIFF_LIBRARY="$env:LTIFF" -DQT_PATH="$env:QT_PATH" -DOpenCV_DIR='C:/vcpkg/installed/x64-windows/share/opencv' -DBOOST_ROOT="$env:BOOST_ROOT" -DWITH_WINTAB=ON -DProtobuf_DIR='C:/vcpkg/installed/x64-windows/share/protobuf/'
        cmake --build . --config Release

    - name: Create Artifact
      env:
        VCINSTALLDIR: 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC'
      run: |
        mkdir artifact | Out-Null
        cd artifact
        cp -Recurse ../stuff portablestuff
        cp ../toonz/build/Release/* .
        ${{ env.QT_ROOT }}/Qt5.15.2_wintab/5.15.2_wintab/msvc2019_64/bin/windeployqt.exe OpenToonz.exe
        cp C:/vcpkg/installed/x64-windows/bin/freeglut.dll .
        cp C:/vcpkg/installed/x64-windows/bin/glew32.dll .
        cp C:/vcpkg/installed/x64-windows/bin/opencv_world.dll .
        cp C:/vcpkg/installed/x64-windows/bin/zlib1.dll .
        cp C:/vcpkg/installed/x64-windows/bin/webp.dll .
        cp C:/vcpkg/installed/x64-windows/bin/libpng16.dll .
        cp C:/vcpkg/installed/x64-windows/bin/jpeg62.dll .
        cp C:/vcpkg/installed/x64-windows/bin/tiff.dll .
        cp C:/vcpkg/installed/x64-windows/bin/liblzma.dll .
        cp C:/vcpkg/installed/x64-windows/bin/libprotobuf.dll .
        cp C:/vcpkg/installed/x64-windows/bin/webpdecoder.dll .

    - uses: actions/upload-artifact@v1
      with:
        name: Opentoonz-${{ runner.os }}-${{ github.sha }}
        path: artifact
